[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/index.js"
healthcheckPath = "/api/salud"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
