[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy; node dist/index.js"
healthcheckPath = "/api/salud"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
